# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: extended
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - torso_slider_joint
    - head_pan_joint
    - head_tilt_joint
    - mico_joint_1
    - mico_joint_2
    - mico_joint_3
    - mico_joint_4
    - mico_joint_5
    - mico_joint_6
    - mico_joint_finger_1
    - mico_joint_finger_2
    - mico_joint_finger_3
    - left_wheel_joint
    - right_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: rb1/mico_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - mico_joint_1
      - mico_joint_2
      - mico_joint_3
      - mico_joint_4
      - mico_joint_5
      - mico_joint_6
  - name: rb1/gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - mico_joint_finger_1
      - mico_joint_finger_2
      - mico_joint_finger_3